### ISSUE TITLE
Not possible to install loqed with v2.0.1

### ISSUE THREAD

**Issue by pjmpessers** [loqed-nl/homey-app#10] opened 2021-03-16 10:04 UTC
Hello.

Thank you for your app. But i stumbled over a problem when i want to install a loqed with app version 2.0.1. It gives: "socked not defined". Switching back to v1.4.1 and i could install it asking for my password and login name.

**Comment by BertvanHoekelen** [comment] 2021-03-16 10:30
Duplicate of #11

**Closed as completed by BertvanHoekelen** 2021-03-16 10:30 UTC
